GLOBAL.setfenv(1, GLOBAL)

-- TUNING.GOBLINKILLER_HEALTH = 150
-- TUNING.GOBLINKILLER_HUNGER = 150
-- TUNING.GOBLINKILLER_SANITY = 200

TUNING.DRAGONFLY_TAUNT_SKILL_COOLDOWN = 20

TUNING.DRAGONFLY_ANGER_MAX = 240
