local GetModConfigData = GetModConfigData
GLOBAL.setfenv(1, GLOBAL)

TUNING.DRAGONFLY_MOUNT_DAMAGE_MULT = GetModConfigData("damage_mult") or 1.0
TUNING.DRAGONFLY_MOUNT_HEALTH_MULT = GetModConfigData("health_mult") or 1.0
TUNING.DRAGONFLY_MOUNT_GROW_DAYS = GetModConfigData("grow_days") or 5

TUNING.DRAGONFLY_TAUNT_SKILL_COOLDOWN = 5
TUNING.DRAGONFLY_TRANSFORM_SKILL_COOLDOWN = 30

TUNING.DRAGONFLY_ANGER_MAX = 300

TUNING.DRAGONFLY_ANGER_ONHIT_REGEN = 5
TUNING.DRAGONFLY_ANGER_ONATTACK_REGEN = 5
TUNING.DRAGONFLY_ANGER_ONRIDERATTACK_REGEN = 15

TUNING.DRAGONFLY_SKILL_COST = {
    TAUNT = 120,
    TRANSFORM = 240,
}
