LOCAL_SCALE_X = -1 / 1.3
LOCAL_SCALE_Y = 1 / 1.3

# down
DOWN_DIR_X_OFFSET = -35
DOWN_DIR_Y_OFFSET = -53

# side
SIDE_DIR_X_OFFSET = -87
SIDE_DIR_Y_OFFSET = -48
SIDE_DIR_SADDLE_SCALE_X = 0.65
SIDE_DIR_SADDLE_X_OFFSET = -80

# up
UP_DIR_X_OFFSET = 51
UP_DIR_Y_OFFSET = -45
