STRINGS.NAMES.DRAGONFLY_MOUNT = "友好龙蝇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLY_MOUNT = "从前是可怕的巨兽，现在是可靠的伙伴。"

STRINGS.NAMES.DRAGONFLY_BELL = "龙蝇铃铛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLY_BELL = "交朋友好简单。"
STRINGS.RECIPE_DESC.DRAGONFLY_BELL = "一个用来召唤你友好龙蝇的铃铛。"