STRINGS.NAMES.DRAGONFLY_MOUNT = "friendly dragonfly"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLY_MOUNT = "Once a fearsome beast, now a trusty companion."

STRINGS.NAMES.DRAGONFLY_BELL = "dragonfly bell"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLY_BELL = "Making friends is so easy."