STRINGS.NAMES.DRAGONFLY_MOUNT = "友好龙蝇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLY_MOUNT = "从前是可怕的巨兽，现在是可靠的伙伴。"

STRINGS.NAMES.DRAGONFLY_BELL = "龙蝇铃铛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLY_BELL = "交朋友好简单。"
STRINGS.RECIPE_DESC.DRAGONFLY_BELL = "一个用来召唤你友好龙蝇的铃铛。"

STRINGS.NAMES.SADDLE_DRAGONFLY = "龙蝇鞍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SADDLE_DRAGONFLY = "一匹适合龙蝇的鞍。"
STRINGS.RECIPE_DESC.SADDLE_DRAGONFLY = "给你的龙蝇朋友装上鞍。"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRAGONFLY_NEED_SADDLE = "我需要给它装上鞍才能骑乘它。"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_NOT_DRAGONFLY_SADDLE = "这个鞍不适合龙蝇。"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRAGONFLY_GOTO_PLAYER = "大家伙，过来这儿！"