# down
DOWN_DIR_X_OFFSET = -35
DOWN_DIR_Y_OFFSET = -15

# side
SIDE_DIR_X_OFFSET = -87
SIDE_DIR_Y_OFFSET = -35
SIDE_DIR_SADDLE_SCALE_X = 0.65
SIDE_DIR_SADDLE_X_OFFSET = -100

# up
UP_DIR_X_OFFSET = 17
UP_DIR_Y_OFFSET = -47
